class prefixGreaterThan3(Exception): pass
class channelNotSpecifiedError(Exception): pass
class MaximumWebhooksReached(Exception): pass
class vkIdNotSpecifiedError(Exception): pass
class vkWallBlockedError(Exception): pass
class subExists(Exception): pass
class noSubs(Exception): pass
class notSub(Exception): pass
class NotAuthenticated(Exception): pass